<!DOCTYPE html>
<meta charset="UTF-8">
<html>
<head>
    <title> Raging Hamsters - Bomberman!</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script><!-- Tether for Bootstrap -->



    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <style type="text/css">
        /* Generated by Font Squirrel (https://www.fontsquirrel.com) on May 31, 2016 */


        .user_info, .game_info {
            visibility: hidden;
            vertical-align: top;
        }
        .current_nav, .current_game, .current_user, .current_content {
            visibility: visible;
            vertical-align: top;
        }
        .content {
            background-color: #ffffff;
        }
    </style>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#games').hide();
            $('#play').hide();
            $('#games_content').hide();
            $('#play_content').hide();

            $('.home').click(function(){
                var id = $(this).html().toLowerCase();
                var cid = id + "_content";
                if( $(".current_nav").attr("id") != id) {
                    $('.current_nav').hide();
                    $('.current_content').hide();
                    $('.current_nav').removeClass('current_nav');
                    $('current_content').removeClass('current_content');
                    $('#'+id).addClass('current_nav');
                    $('#'+cid).addClass('current_content');
                    $('#'+id).show();
                    $('#'+cid).show();
                }

            });

            $('.user_nav').click(function(){
                var id = $(this).html();
                if( $('.current_user').attr("id") != id && id.toLowerCase().indexOf("_game") <= 0 ){
                    $('.current_user').hide();
                    $('.current_user').removeClass('current_user');
                    $('#'+id).addClass('current_user');
                    $('#'+id).show();
                }
            });

            $('.game_nav').click(function(){
                var id = $(this).html();
                id = id.slice(0, id.indexOf("'s")) + "_game";
                if($('.current_game').attr("id") != id){
                    $('.current_game').hide();
                    $('.current_game').removeClass('current_game');
                    $('#'+id).addClass('current_game');
                    $('#'+id).show();
                }

            });

        //Do the same for Game and User Navigation
        });
    </script>
    <img src = "http://ec2-52-24-234-176.us-west-2.compute.amazonaws.com/Title.png" border="0px"/>
    <?php
    /**
     * Created by PhpStorm.
     * User: Jasmine
     * Date: 5/26/2016
     * Time: 9:37 PM
     */

    require_once('objects.php');
    $server_name = "127.0.0.1";
    $username = "root";
    $password = "password";
    $table = "raginghamsters";
    $conn = new mysqli($server_name, $username, $password, $table);
    $userContent = "";
    $gameContent = "";
    $counter = 0;

    //Getting Game and User information for later :)
    $userList = Array();
    $gameList = Array();
    if($conn->connect_error){
        echo 'waddap';
        die("Connection Failed: ".$conn->connect_error);
    }
    //echo 'Connected to MySQL Server';

    $sql ="SELECT * FROM `users`";
    if(!$result = $conn->query($sql)){
        echo "No Users Found!";
    }

    while( $row = $result->fetch_assoc() ){
        array_push($userList, new Player($row['username'], $row['kills'], $row['deaths'], $row['wins'], $row['games'], $row['status']));
    }

    $sql = "SELECT host, players, player1, p1score, player2, p2score, player3, p3score, player4, p4score FROM games, gamestats WHERE games.ipaddr = gamestats.gameip";
    if(!$result = $conn->query($sql)){
        echo "No Current Games";
    }
    while($row = $result->fetch_assoc()){
        array_push($gameList, new Game($row['host'], $row['players'], $row['player1'], $row['p1score'],
            $row['player2'], $row['p2score'],
            $row['player3'], $row['p3score'],
            $row['player4'], $row['p4score']));
    }

    //put userinfo into divs
    foreach($userList as &$user){
        if($counter == 0 ){
            $content =  "<div class='current_user' id='".$user->username."'>";
        }
        else {
            $content =  "<div class='user_info' id='".$user->username."'>";
        }
        $content .= $user->to_str();
        $content .= "</div>";
        $userContent .= $content;
        $counter++;
    }
    $counter = 0;

    foreach ($gameList as &$game){
        if($counter == 0){
            $gcontent = "<div class='current_game' id='".$game->host."_game'>";
        } else {
            $gcontent = "<div class='game_info' id='".$game->host."_game'>";
        }
        $gcontent .= $game->to_str();
        $gcontent .= "</div>";
        $gameContent .= $gcontent;
        $counter++;
    }

    // Closing connection
    mysqli_close($conn);

    ?>

</head>

<body class="col-md-12" style="background-color:#bae8ff; border-radius: 25px;">
<table class = "col-md-12">
    <tr>
        <td class="col-md-2" style="vertical-align: top;">
            <div id = "nav1-main" >
                <ul class="nav nav-pills nav-stacked" style="background-color:#ffffff;">
                    <li role="presentation" class="active"><a class="home" id="show_users" title = "Users">Users</a></li>
                    <li role="presentation"><a class="home" id ="show_games" title="Game Stats">Games</a></li>
                    <li role="presentation"><a class="home" id="play_game" title="Play Now!">Play</a></li>
                </ul>
            </div>

        </td>
        <td class = "col-md-2" style="background-color:#ffffff; vertical-align: top;">
            <div class = "current_nav" id = "users">
               <h3><b>Users:</b></h3>
                <h4><b>Online:</b></h4>
                <?php
                //ADD LINKS HERE
                foreach($userList as &$user){
                    if($user->status == "ONLINE" || $user->status =="GAME"){
                        //double check this, you got sleepy.
                        echo "<a class='user_nav' id='show_user' title='user'>".$user->username."</a><br>";
                    }
                }
                echo "<h4><b>Offline:</b></h4>";
                //ADD LINKS HERE
                foreach($userList as &$user){
                    if($user->status == "OFFLINE"){
                        echo "<a class='user_nav' id='show_user' title='user'>".$user->username."</a><br>";
                    }
                }
                ?>
            </div>
            <div id = "games">
                <h3><b>Active Games</b></h3>
                <?php
                foreach($gameList as &$game){
                    echo "<a class='game_nav' id='show_game' title='game'>".$game->host."'s Game </a><br/>";
                }
                    ?>
            </div>
            <div id = "play">
                <h3><b><center>How To Play:</center></b></h3>
                Welcome to Bomberham! Use the arrow keys to navigate your hamster across the game scene.
                Press Space to drop bombs! Be the last hamster standing for a win!
            </div>

        <td class = "col-md-8" style="background-color:#ffffff; vertical-align: top;">
            <div class ="current_content" id="users_content">
                <?php echo $userContent; ?>
            </div>
            <div id="games_content">
                <?php echo $gameContent; ?>
            </div>
            <div id="play_content">
                <!-- If we ever get this part working >_> -->
            </div>

        </td>
    </tr>
</table>
</body>

</html>
